function history_to_csv(fname, hist)
T = table(hist.iter, hist.EE, hist.Rsum, hist.Ptot, hist.cost, hist.grad_theta_norm, ...
    hist.grad_p_norm, hist.penalty_power, hist.penalty_qos_dl, hist.penalty_qos_ul, ...
    hist.mean_sinr_dl_db, hist.mean_sinr_ul_db, hist.mean_direct, hist.mean_reflect, ...
    hist.reflect_direct_ratio, hist.active_bs_per_user, hist.avg_ris_load, ...
    hist.step_mu, hist.accepted_ls_trials, hist.phase_change_norm, hist.power_change_norm, ...
    'VariableNames', {'iter','EE','Rsum','Ptot','cost','grad_theta_norm','grad_p_norm', ...
    'penalty_power','penalty_qos_dl','penalty_qos_ul','mean_sinr_dl_db','mean_sinr_ul_db', ...
    'mean_direct','mean_reflect','reflect_direct_ratio','active_bs_per_user','avg_ris_load', ...
    'step_mu','accepted_ls_trials','phase_change_norm','power_change_norm'});
writetable(T, fname);
end
