function h = init_history(T)
fields = {'iter','EE','Rsum','Ptot','cost','grad_theta_norm','grad_p_norm', ...
    'penalty_power','penalty_qos_dl','penalty_qos_ul','mean_sinr_dl_db', ...
    'mean_sinr_ul_db','mean_direct','mean_reflect','reflect_direct_ratio', ...
    'active_bs_per_user','avg_ris_load','step_mu', ...
    'accepted_ls_trials','phase_change_norm','power_change_norm', ...
    'dl_desired_to_interference','dl_desired_to_noise', ...
    'ul_desired_to_interference','ul_desired_to_noise'};
for i = 1:numel(fields)
    h.(fields{i}) = zeros(T,1);
end
end
